{
    'name': 'SaaS Client',
    'version': '13.0.1.0.0',
    'author': 'Ivan Yelizariev, Nicolas JEUDY',
    'license': 'LGPL-3',
    'category': 'SaaS',
    "support": "apps@it-projects.info",
    'website': 'https://it-projects.info',
    'depends': [
        'access_limit_records_number',
        'auth_oauth',
        'auth_oauth_check_client_id',
        'auth_oauth_ip',
        'mail',
        'saas_base',
        'web_settings_dashboard',
    ],
    'external_dependencies': {
        'python': ['simplejson'],
    },
    'data': [
        'views/saas_client.xml',
        'views/res_config.xml',
        'security/rules.xml',
        'security/groups.xml',
        'data/ir_cron.xml',
        'data/auth_oauth_data.xml',
        'data/ir_config_parameter.xml',
        'data/ir_actions.xml',
    ],
    'installable': True,
    'qweb': [
        'static/src/xml/saas_dashboard.xml',
    ],
}
